apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: virtex-erp
build:
  artifacts:
    - image: ghcr.io/virtex/api-gateway
      context: .
      docker:
        dockerfile: apps/virtex-api-gateway/Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - platform/kubernetes/manifests/base/deployment.yaml
deploy:
  kubectl: {}
