apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: virtex-erp
build:
  artifacts:
    - image: ghcr.io/virtex/edge-portal-app
      context: .
      docker:
        dockerfile: apps/edge/portal/app/Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - platform/kubernetes/manifests/base/deployment.yaml
deploy:
  kubectl: {}
