export enum AssetStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', DISPOSED = 'DISPOSED', MAINTENANCE = 'MAINTENANCE' }
export enum DepreciationMethod { STRAIGHT_LINE = 'STRAIGHT_LINE', DECLINING_BALANCE = 'DECLINING_BALANCE', UNITS_OF_PRODUCTION = 'UNITS_OF_PRODUCTION' }
