export enum ProjectStatus { PLANNED = 'PLANNED', IN_PROGRESS = 'IN_PROGRESS', COMPLETED = 'COMPLETED', ON_HOLD = 'ON_HOLD', CANCELLED = 'CANCELLED' }
export enum TaskStatus { TODO = 'TODO', IN_PROGRESS = 'IN_PROGRESS', REVIEW = 'REVIEW', DONE = 'DONE' }
