# Dynamic configuration
http:
  routers:
    portal-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/portal`)"
      service: portal-service
      entryPoints:
        - websecure
      tls: {}

    pos-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/pos`)"
      service: pos-service
      entryPoints:
        - websecure
      tls: {}

    identity-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/identity-service`)"
      service: identity-service
      entryPoints:
        - websecure
      tls: {}

    inventory-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/inventory-service`)"
      service: inventory-service
      entryPoints:
        - websecure
      tls: {}

    billing-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/billing-service`)"
      service: billing-service
      entryPoints:
        - websecure
      tls: {}

  services:
    portal-service:
      loadBalancer:
        servers:
          - url: "http://bff-portal:3100"
    pos-service:
      loadBalancer:
        servers:
          - url: "http://pos-service:3008"
    identity-service:
      loadBalancer:
        servers:
          - url: "http://service-identity:3000"
    inventory-service:
      loadBalancer:
        servers:
          - url: "http://service-inventory:3001"
    billing-service:
      loadBalancer:
        servers:
          - url: "http://service-billing:3003"

tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.crt
      keyFile: /etc/traefik/certs/cert.key
