export enum CustomerType { INDIVIDUAL = 'INDIVIDUAL', COMPANY = 'COMPANY', GOVERNMENT = 'GOVERNMENT' }
export enum OpportunityStage { PROSPECTING = 'PROSPECTING', QUALIFICATION = 'QUALIFICATION', PROPOSAL = 'PROPOSAL', NEGOTIATION = 'NEGOTIATION', CLOSED_WON = 'CLOSED_WON', CLOSED_LOST = 'CLOSED_LOST' }
